name: Update version
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    name: "Bump Version On Main"
    runs-on: ubuntu-latest

    steps:
      - name: "Use checkout v2"
        uses: actions/checkout@v2
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "MINOR"
          major-wording: "MAJOR"
          tag-prefix: "v"
          target-branch: "main"
          commit-message: "Update version"
